site_name: Problema de condición inicial

theme:
  name: "material"

vav:
  - index.md
  - tutorials.md
  - reference.md
  - explanation.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [Dynamics]
          site_dir: docs


markdown_extensions:
  - pymdownx.arithmatex:
     generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
